---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-scaler-config-1
  labels:
    app: simple-scaler
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss1"
    data-dir = "/var/lib/simple-scaler/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-scaler-1:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-scaler-1:2379"
    initial-cluster = "ss1=http://simple-scaler-1:2380,ss2=http://simple-scaler-2:2380,ss3=http://simple-scaler-3:2380"

    [azure]
    max-nodes = 2
    tenant = "TENENT CODE HERE"
    resource-group = "RESOURCE GROUP HERE"
    name-template = "az-worker-"
    sp-appid = "SERVICE PRINCIPAL APP ID HERE"
    sp-password = "SERVICE PRINCIPAL PASSWORD HERE"

  kubeconfig: |
    KUBECONFIG FILE HERE
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-scaler-config-2
  labels:
    app: simple-scaler
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss2"
    data-dir = "/var/lib/simple-scaler/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-scaler-2:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-scaler-2:2379"
    initial-cluster = "ss1=http://simple-scaler-1:2380,ss2=http://simple-scaler-2:2380,ss3=http://simple-scaler-3:2380"

    [azure]
    max-nodes = 2
    tenant = "TENENT CODE HERE"
    resource-group = "RESOURCE GROUP HERE"
    name-template = "az-worker-"
    sp-appid = "SERVICE PRINCIPAL APP ID HERE"
    sp-password = "SERVICE PRINCIPAL PASSWORD HERE"

  kubeconfig: |
    KUBECONFIG FILE HERE

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-scaler-config-3
  labels:
    app: simple-scaler
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss3"
    data-dir = "/var/lib/simple-scaler/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-scaler-3:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-scaler-3:2379"
    initial-cluster = "ss1=http://simple-scaler-1:2380,ss2=http://simple-scaler-2:2380,ss3=http://simple-scaler-3:2380"

    [azure]
    max-nodes = 2
    tenant = "TENENT CODE HERE"
    resource-group = "RESOURCE GROUP HERE"
    name-template = "az-worker-"
    sp-appid = "SERVICE PRINCIPAL APP ID HERE"
    sp-password = "SERVICE PRINCIPAL PASSWORD HERE"

  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
      KUBECONFIG FILE HERE
