---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ss1-data
  labels:
    app: simple-scaler-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ss2-data
  labels:
    app: simple-scaler-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ss3-data
  labels:
    app: simple-scaler-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

