name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build, test and public image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
        echo exit code $?
        git tag --list
        echo "APP_VERSION=$(git describe --tags --dirty=+)"

    - name: Get short git commit hash
      id: hash
      run: echo "::set-output name=hash::${GITHUB_SHA::7}"

    - name: Get version number
      id: version
      run: echo "::set-output name=version::$(git describe --tags --dirty=+)"

    - name: Get base hash
      id: base-hash
      run: echo "::set-output name=base-hash::$(sha512sum src/simple-scaler.asd | cut -b 1-8)"

    - name: Test if base exists
      id: base-exists
      run: echo "::set-output name=base-exists::$(podman manifest inspect quay.io/atgreen/simple-scaler-base:${{ steps.base-hash.outputs.base-hash }} > /dev/null 2>&1 && echo 'EXISTS')"

    - name: Prepare base image
      id: build-base
      uses: redhat-actions/buildah-build@v2
      with:
        image: simple-scaler-base
        tags: ${{ steps.base-hash.outputs.base-hash }} latest
        dockerfiles: |
          build/Dockerfile.base
      if: ${{ steps.base-exists.outputs.base-exists != 'EXISTS' }}

    - name: Push base to quay.io
      id: push-base-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-base.outputs.image }}
        tags: ${{ steps.build-base.outputs.tags }}
        registry: quay.io/atgreen
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      if: ${{ steps.base-exists.outputs.base-exists != 'EXISTS' }}

    - name: Build application image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: simple-scaler
        tags: latest ${{ steps.hash.outputs.hash }} ${{ steps.version.outputs.version }}
        dockerfiles: |
          build/Dockerfile
        build-args: |
          APP_VERSION=${{ steps.version.outputs.version }}

    - name: Test
      run: |
        podman play kube test/test-pod.yml
        timeout -s TERM 45 bash -c \
          'while [[ "$(curl -s -o /dev/null -L -w ''%{http_code}'' ${0})" != "200" ]];\
            do echo "Waiting for ${0}" && \
            sleep 2;\
           done' http://localhost:8080/health || true
         echo "==== Container Logs ================================"
         podman pod logs simple-scaler-pod

    - name: Push to registry
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/atgreen
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
